services:
  nginx:
    image: nginx:alpine
    container_name: proj_estoque_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - frontend
      - backend
    restart: unless-stopped

  app:
    build:
      context: .
      target: runner
    image: proj-estoque-app:latest
    container_name: proj_estoque_app
    expose:
      - "3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/proj_estoque
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: proj_estoque
      JWT_SECRET: #copiar do .env
      JWT_EXPIRES_IN: 1d
      BCRYPT_SALT_ROUNDS: 10
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped

  node_cli:
    image: node:20-alpine
    container_name: proj_estoque_node_cli
    working_dir: /app
    volumes:
      - .:/app
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: proj_estoque
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 1d
      BCRYPT_SALT_ROUNDS: 10
    networks:
      - backend
    profiles:
      - cli
    entrypoint: ["node", "commands.js"]

  db:
    image: postgres:16-alpine
    container_name: proj_estoque_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proj_estoque
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d proj_estoque"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true